name: Greeting from XIE_JUNJIE
on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        My_VAR: Hi there! My name is
        FIRST_NAME: JUNJIE
        LAST_NAME: XIE
      run: |
        echo $MY_VAR $FIRST_NAME $LAST_NAME

